[package]
name = "torquelearn"
version = "0.2.0"
edition = "2018"

[dependencies]
glob = "0.3.0"
markdown = "0.3.0"
copy_dir = "0.1.2"
rocket = "0.5.0-rc.1"
regex = "1.5.4"
walkdir = "2"
wasm-bindgen = "0.2"
